name: popuppros
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.0.0

  get: ^4.6.5
  image_picker: ^0.8.5+3
  figma_squircle: ^0.5.3
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
  firebase_database: ^9.0.7
  firebase_storage: ^10.2.8
  firebase_core_platform_interface: 4.5.1

  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  flutter_share: ^2.0.0
  flutter_mailer: ^2.0.1
  flutter_screenutil: ^5.5.3+2

  launch_review: ^3.0.1
  connectivity_plus:
  crypto: ^3.0.2
  flutter_otp_text_field: ^1.1.1
  country_code_picker: ^2.0.2
  country_state_city_picker: ^1.2.8

  google_maps_flutter: ^2.1.4
  location: ^4.3.0
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  percent_indicator: ^4.2.2

  dropdown_button2: ^1.9.2
  google_sign_in: ^5.4.4
  platform_device_id: ^1.0.1
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15
  swipe_cards: ^2.0.0+1

  freezed_annotation: any
  json_annotation: any
  logger: any
  provider: any
  flutter_time_picker_spinner: ^2.0.0
  need_resume: ^1.0.7+1
  flutter_switch: ^0.3.2
  dotted_border: ^2.0.0+3

  intl: any
  flutter_localizations:
      sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: any
  freezed: any
  build_runner: any

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300

    - family: Qwigley
      fonts:
        - asset: assets/fonts/Qwigley-Regular.ttf